# Generated by Django 2.0.4 on 2018-04-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GoalStatus',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(null=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.GoalStatus')),
            ],
            options={
                'verbose_name_plural': 'ScrumyGoal',
            },
        ),
        migrations.CreateModel(
            name='Scrumyuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.TextField()),
                ('Developer', models.CharField(default='Developer', max_length=200)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Role')),
            ],
            options={
                'verbose_name': 'Scrumyuser',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Scrumyuser')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Task'),
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Scrumyuser'),
        ),
    ]
